# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: node-latest
    steps:
      - name: Build
      - run: npm run build
      - name: Deploy
      - run: npm run deploy
