# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v3
      - name : Build
        run : 
          npm 
          npm run build
      - name : Publish
        run : 
          npm run deploy
        env : 
          NODE_AUTH_TOKEN : ${{secret.NPM_TOKEN}}
        
            
      
